### ISSUE TITLE
regex for file matching is restrictive

### ISSUE THREAD

**Issue by Morriz** [RobbinHabermehl/gulp-angular-translate#3]
Your assumption that the naming translation files adhere to your standard is too restrictive.
You should allow "**/*.json" to be globbed.
Want me to make a pull request?

**Comment by Morriz** [comment]
I can't seem to make the glob pattern appear correctly here. The asterisk before the .json is omitted on the screen. I don't know why github makes it so...

**Comment by RobbinHabermehl** [comment]
Discussed in PR #4.
